# Demonstrate Klocwork Full Integration Analysis

trigger:
  branches:
    include:
    - main

variables:
  # Validate Portal Variables
  VD_PROJNAME: 'K_Cpp_Win10CI_Azure'
  VD_SVR_PORTAL: 'localhost'
  VD_SVR_PORT: '8080'
  
  # Klocwork Tools
  KW_TOOLS: 'C:\Perforce\Klocwork\kwbuildtools22.3\bin'
  KW_INJECTFILE: 'kwinject.out'

  # Local Project Workspace
  # WORKSPACE: $(PWD)

pool: Default

stages:
- stage: Analysis
  jobs:
  - job: Build
    steps:
    - script: |
        echo hello
        whoami
        
        # C:\Perforce\Klocwork\kwbuildtools22.3\bin\kwinject.exe make clean all
        # C:\Perforce\Klocwork\kwbuildtools22.3\bin\kwbuildproject.exe --url http://localhost:8080/K_Cpp_Win10CI_Azure -o kwtables -f kwinject.out
        # C:\Perforce\Klocwork\kwbuildtools22.3\bin\kwadmin --url http://localhost:8080 load K_Cpp_Win10CI_Azure kwtables
