# Demonstrate Klocwork Full Integration Analysis

trigger:
  branches:
    include:
    - main

variables:
  # Validate Portal Variables
  VD_PROJNAME: 'K_Cpp_Win10CI_Azure'
  VD_SVR_PORTAL: 'localhost'
  VD_SVR_PORT: '8080'
  
  # Klocwork Tools
  KW_TOOLS: 'C:\Perforce\Klocwork\kwbuildtools22.3\bin'
  KW_INJECTFILE: 'kwinject.out'

  # Local Project Workspace
  WORKSPACE: $(PWD)

pool:
  name: WIN10VM64CI

stages:
  - stage: build
    displayName: Build Project
    jobs:
      - job: build
        steps:
          - script: |
            $(KW_TOOLS)\kwinject.exe make clean all
